version: "3.9"

services:
  db:
    image: maximka512/bd:preloaded-16d
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: "1"
      POSTGRES_DB: fulfillment
      PGDATA: /var/lib/postgresql/seeddata
    ports:
      - "5432:5432"
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - appnet

  server:
    image: maximka512/server
    environment:
      PORT: 5000
      DB_NAME: fulfillment
      DB_USER: root
      DB_PASSWORD: "1"
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: random_secret_key123
    ports:
      - "5000:5000"
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - appnet

  client:
    image: maximka512/client
    environment:
      REACT_APP_API_URL: "http://server:5000/"
    ports:
      - "3000:3000"
    depends_on:
      - server
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    networks:
      - appnet

  pgadmin:
    image: dpage/pgadmin4:8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8888:80"
    user: "5050:5050"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      placement:
        constraints:
          - node.role == manager
    networks:
      - appnet

volumes:
  db_data:
  pgadmin_data:

networks:
  appnet:
    external: true
    name: app_appnet
